name: Docker Socket Proxy
version: 1.0
slug: docker_socket_proxy
description: Expose Docker socket securely using lscr.io/linuxserver/socket-proxy.
url: https://github.com/Ja9ad335h/ha-addon
startup: "services"
boot: "auto"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - "share"
ports:
  2375/tcp: 2375
apparmor: false
options:
  port: 2375
  CONTAINERS: true
  NETWORKS: true
  TASKS: true
  SERVICES: true
  INFO: true
  POST: false
devices:
  - "/var/run/docker.sock:/var/run/docker.sock:ro"
read_only: true
tmpfs: "/run"
