name: Docker Socket Proxy
version: 1.0
slug: docker_socket_proxy
description: Expose Docker socket securely using lscr.io/linuxserver/socket-proxy.
url: https://github.com/Ja9ad335h/ha-addon
startup: "services"
boot: "auto"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - "share"
ports:
  2375/tcp: 2375
apparmor: false
environment:
  - CONTAINERS=1         # Enables access to container-related endpoints
  - NETWORKS=1           # Enables access to network-related endpoints
  - TASKS=1              # Enables access to task-related endpoints
  - SERVICES=1           # Enables access to service-related endpoints
  - INFO=1               # Enables access to Docker system info
  - POST=0               # Disables access to POST endpoints
volumes:
  - "/var/run/docker.sock:/var/run/docker.sock:ro"
read_only: true
tmpfs: "/run"
