# Use the LinuxServer socket proxy image
FROM lscr.io/linuxserver/socket-proxy:latest

# Default environment variables for the add-on
ENV CONTAINERS=1
ENV NETWORKS=1
ENV TASKS=1
ENV SERVICES=1
ENV INFO=1
ENV POST=0
